### ISSUE TITLE
Ability to charge money for apps / paid apps

### ISSUE THREAD

**Issue by jancborchardt** [owncloud/appstore-issues#31]
To further push the ownCloud ecosystem, it might be beneficial if people can charge money for their apps. I have been asked for that multiple times by interested developers, and I guess this would help make app development sustainable.

What do you think @karlitschek @jospoortvliet @DeepDiver1975

**Comment by MorrisJobke** [comment]
cc @felixboehm

**Comment by jospoortvliet** [comment]
Hmm, you can charge money but people can of course circumvent it. Proprietary ownCloud apps are not possible due to the AGPL, unless you have the Enterprise Edition (which has a proprietary license), both as user and developer.

I do think the idea is interesting but it would boil down to donating (flatr integration for example?) unless, again, you'd target enterprises of course. That could indeed be interesting.

**Comment by jancborchardt** [comment]
Paying does not mean proprietary, as you know. The Files, Notes and News apps for Android and iOS are paid-for but still open source.

Open source development needs to be sustainable too. Flattr is not really used anymore (at least not by many people) and paying directly for an app seems to be the widespread model.

**Comment by MorrisJobke** [comment]
> Hmm, you can charge money but people can of course circumvent it. Proprietary ownCloud apps are not possible due to the AGPL, unless you have the Enterprise Edition (which has a proprietary license), both as user and developer.

I have to agree with @jancborchardt : Why shouldn't it be possible to simply pay for a one click install solution? If you can't effort 1€ (or something like that) for this you can also copy the tar ball to your server. ;)

**Comment by jancborchardt** [comment]
> you can also copy the tar ball to your server

Or rather you would then need to load it from Github and something like install dependencies manually. Whatever the dev decides.

**Comment by jospoortvliet** [comment]
Ok, as long as it's clear that apps have to be open source, I am all for making it possible to charge money for them. The challenge is payment system - this is quite difficult to handle, I think.

So the question is about who does the work and how ;-)

**Comment by oparoz** [comment]
I'm glad someone has opened that can of worm, it's been bothering me for a while.

## Licensing

It would be great if some restrictions could be lifted on specific parts of the code to give clear licensing options to devs.
Currently they have to take their chances and license their work how they see fit, depending on the result of their analysis on if the law considers their work to be derivative work or not.

Looking around to what has happened in the Open Source CMS (Wordpress, Joomla, etc.) or e-commerce markets (Magento, Prestashop, etc.) where there are : 
- thriving apps ecosystems
- apps of great quality, which are supported
- reasonable prices (free market)
- app/themes clubs

We can see that the (A)GPL is not necessarily a barrier to being successful, but we have to bear in mind that some devs don't consider their work to fall under the GPL.

## Selling apps

### Apps store

It's working for the mobile side where users have to pay €1 to download an app they really want to use and it would be great to have that both in the app store and in ownCloud itself (buy instead of download button). There are plenty of solutions allowing the collection of payments in a safe way (Stripe, Paymentwall (anonymous), etc. )

The fees should cover the development and maintenance costs if there is really a market for apps.

### Specs
- If using the facility offered by ownCloud, there would be a processing fee taken off the market price (hopefully, not 30% ;))
- Developers would get rewarded for their efforts without having to ask users to register on yet another platform
- ownCloud could offer better stats that the download counter
- This would require having an account on the app store, which isn't a bad thing
- Nobody is forcing users to buy apps. Free apps continue to live
- Developers can use a separate licensing system if they wish. Selling addons for their apps per example.
- A decision needs to be made regarding ads. There is currently no privacy rules for the app store (https://github.com/owncloud/appstore-issues/issues/29). Devs are free to collect anything they want

### Dev shops

It's missing as people seem to have focused on reselling cloud space rather than apps and themes, but nothing is stopping devs to sell their AGPL and non-AGPL plugins, themes and services.

I'm guessing the tools were too immature to be able to build a profitable business before this year, but there is still one hurdle from my point of view: the market (paying customers) is too small.

**Comment by MorrisJobke** [comment]
> It should be possible to use any non-free license for apps. Period.

This is not allowed if you use the community version of ownCloud. AGPL forbids to run non AGPL compatible code together with AGPL code.

If you have the enterprise version you get a non-AGPL licensed version - see https://owncloud.com/owncloud-server-or-enterprise-edition/

**Comment by oparoz** [comment]
I thought, you could limit the scope of the license, just like you can decide to make it completely commercial.

Since that's not the case, I hope ownCloud will be able to sell €39.99 licenses with no support to home/SME users so that devs can bring lots of quality apps to these users. I don't see the app store take off without it, but maybe you have some examples of stores where this model (agpl3 only apps) actually works?

**Comment by jancborchardt** [comment]
Wordpress is licensed under GPLv2+, maybe for that reason: https://wordpress.org/about/gpl/

**Comment by jospoortvliet** [comment]
@oparoz if/once there is demand, I think something like that would be possible. Until then, bounty source and stuff like that is kind-of it. Besides, the app store would need quite some work for this...

It is something we will keep an eye on, though. I think it will be relevant at some point in the future. So let's keep this issue open.

**Comment by oparoz** [comment]
> Wordpress is licensed under GPLv2+

@jancborchardt - I've done some research and have updated my post above. I think both licenses allow devs to do the same thing (except for the network provision in the AGPL), so there isn't really a licensing issue (like I thought there was). It's more of a market one like @jospoortvliet has just mentioned. No demand = no business.

> This is not allowed if you use the community version of ownCloud. AGPL forbids to run non AGPL compatible code together with AGPL code.

@MorrisJobke I've checked and it's not true. Section 7 allows ownCloud to license parts differently

> ... If additional permissions apply only to part of the Program, that part may be used separately under those permissions, but the entire Program remains governed by this License without regard to the additional permissions....

And there is also the fact that you can write apps or components for apps which can be considered not to form derivative work, but it's probably not worth the risk for small apps.

**Comment by jospoortvliet** [comment]
@oparoz what @MorrisJobke still stands. Yes, the separate parts of any GPL or AGPL licensed app can have other licenses in addition and they can, separate, still be used. So you could (dual) license the Gallery app under the, say, BSD, and then somebody could integrate it into another cloud technology using the BSD license, not having to care about the AGPL requirement from the rest of the code of ownCloud.

That's cool but has nothing to do with the ability of people to make an ownCloud server available with proprietary parts. If you do that, you have to abide by the AGPL and the only way to get an exception is to use the non-AGPL version of ownCloud (enterprise edition). In simple terms: if you want to modify ownCloud but not contribute back to the community, pay Inc. so our engineers can eat.

The "can't be considered derivative work" is a more complicated matter. If you use public ownCloud API's, our official stance will be that what you wrote is a derivative work, period. Good luck challenging it in court...

Now please do keep in mind that as long as you don't "distribute" following the terms of the AGPL, you're good. So you could totally sell a proprietary ownCloud app to a company which uses it exclusively internal. If they would, however, give access to their ownCloud to customers, partners or otherwise non-employees, they would be in breach of the AGPL unless they hand over the source of the proprietary app under the AGPL. Moreover, you could, under the same rule, develop proprietary changes internally.

However, very few corporate lawyers will be happy with taking that risk: if an employee, accidentally, shares a public link to a customer, partner or boy/girlfriend, the company would be liable to a lawsuit. Better just get the Enterprise edition. And yes, for that, you can make proprietary apps.

Note that, as I said before, you can ask money for AGPL apps too, we ask money for the ownCloud clients on the iOS and Google Play stores. Of course, the amount you can ask is limited as people can get the apps for free if they are willing to put in some extra effort. I wouldn't oppose adding a paid apps section to the app store - people who can't or don't want to pay can simply grab the code from github and install themselves. That is, as I said, why this issue can and should remain open. The main blockers are, from my perspective, demand and the resources needed to implement a payment system.

Note that none of what I say is or can be seen as legal advice - I am NOT a lawyer. Consult somebody who is if you need legal advice. Nor is this an official statement from ownCloud, Inc. - just me, as fallible employee, talking to the best of my limited knowledge on a public forum.

**Comment by oparoz** [comment]
> That's cool but has nothing to do with the ability of people to make an ownCloud server available with proprietary parts

After re-reading it, I think you're right, that specific line works well with your Gallery example, but the whole section 7 allows the copyright holder to supplement the license with additional permissions, so the APIs could still be freed from the AGPL.

> In simple terms: if you want to modify ownCloud but not contribute back to the community

That's not what it's about, an app does not modify ownCloud core and has no impact on the livelihood of Inc. developers. If anything, it improves core since app devs are more likely to try and fix core if they can't offer the level of service they want with their app because of issues in core

>  If you use public ownCloud API's, our official stance will be that what you wrote is a derivative work, period. Good luck challenging it in court...

The "good luck" goes both ways. The concept of plugins being derivative work has never been validated in a court of law and most IP protection as used for art doesn't work well for software. If I make a painting using the same special canvas, paint and brushes, available as a pack called ownPaint, is my painting considered derivative work of ownPaint? I don't think so, but it is a very complex issue. As you can witness in the CMS camp, many have taken a liberal approach and WP per example has decided not to fight non-GPL apps, but to promote those playing ball.

> So you could totally sell a proprietary ownCloud app to a company which uses it exclusively internal.

You're sure about that? To me, if I sell an app which I consider to be derivative work of ownCloud, I'm already distributing modified code, since it's not used internally by me and so I must share my changes. On the other hand if I modify the instance of a customer, then he doesn't need to share those changes back.

> people who can't or don't want to pay can simply grab the code from github and install themselves

Not necessarily. The code can be made available only to paying customers via the dev's portal. People wanting to have it for free would have to get it an alternative way, again, just like for some Worpdress plugins. At the end of the day, people are paying for support and those who need it or those who want to support the dev will get the paid version, but there is nothing a dev can do against people torrenting the app.

All things said, I think it's much simpler for devs to simply sell their AGPL app via their portal if they believe it's worth it, but I don't think it's the only way, especially for pure JS apps, apps which need to use an external service or for plugins within an app (extra features).

IANAL either and my comments cannot be taken as legal advice either. It's just an analysis of the complex situation, based on precedents in the industry, US and EU legal cases and some legal advice.

**Comment by DeepDiver1975** [comment]
fixed with marketplace.owncloud.com
