### ISSUE TITLE
Archive verification on upload ...

### ISSUE THREAD

**Issue by DeepDiver1975** [owncloud/appstore-issues#32]
We should really have a strict archive format which is checked before published in the appstore.

Can we add a validation step for the archives in the submit page?

Checks to be performed from my pov:
-    archive format (zip, tar)
-    archive structure (proper app name in root folder)
-    version in archive (info.xml and appinfo/version and in the appstore match)
-    ocsid matches
-    run code checker (to be discussed)

**Comment by ghost** [comment]
Hi,

not quite sure if this the right place to post this but some app devs disagree with the current install method and probably also with that stricter rules:

https://github.com/fcturner/passwords/issues/56#issuecomment-136314917 and

> This app cannot be installed from within ownCloud, since this system demands repackaging of releases and kills the possibility to freely use GitHub master versions.

https://apps.owncloud.com/content/show.php/Passwords?content=170480

**Comment by ghost** [comment]
Exactly. If I may drop in and explain myself:
I really like ownCloud and I like really developing apps for it, so others can use them.

As an app dev (of 'passwords' and 'theme switcher') I don't want to compensate for clumsiness on the side of ownCloud itself, because I think it should be solved there (I'm happy to help!). 

This clumsiness is defined by the fact that, to make app installations work in ownCloud itself, I must use the open-source platform GitHub in another way it was intended to, and it makes it more complex to 'just' release a new version. I test my app versions thoroughly, so just a push on the Release button is what GitHub intended. Now, I need to download my own release first, repack it (which is prone to errors), upload it and release it again. By doing so, GitHub loses part of their strength in their branch and tagging system, as it partly blows all options to use GitHub masters.

Albeit being enthusiastic about ownCloud, on app installation ownCloud should just:
- strip off any branch attached to the folder name, **or**
- allow multiple versions in one /apps/ location of the same app in which ownCloud ignores previous versions (better yet: actively asks permission to delete those folders on an update), **or**
- move old app versions to another folder, allowing to restore them (if there are no database structure changes)

I say this, because (in my opinion) _GitHub's release system should prevail over ownCloud installation system_. If you think otherwise, we might never meet in the middle :wink: 

Please embrace app devs by fixing this :pray:

**Comment by DeepDiver1975** [comment]
the current appstore is dead ....
