### ISSUE TITLE
OC version filter in apps portal

### ISSUE THREAD

**Issue by dmnc-net** [owncloud/appstore-issues#9]
Hi, apps portal http://apps.owncloud.com/ should contain ownCloud version filter, it will provide better user experience while browsing apps. Thanks.

**Comment by blackcrack** [comment]
jupp, someting like : 
![Image of a version filter](http://www.blackysgate.de/files/folder-root/owncloud/apps.owncloud.com.png)

and there the topic : 
https://forum.owncloud.org/viewtopic.php?f=34&t=32228&p=104051#p104051

it's also well for the others like kde and gnome and iconthemes .. because this is connected with the opendesktop community like i have view ..( however, I can be also mistaken )

best regards
Blacky

**Comment by DeepDiver1975** [comment]
appstore is dead - long live the marketplace!
For suggestion please head over to https://github.com/owncloud/marketplace-issues/
